export const SET_FRIENDS_REQUEST = "SET_FRIENDS_REQUEST";
export const SET_FRIENDS_FAILURE = "SET_FRIENDS_FAILURE";
export const SET_FRIENDS = "SET_FRIENDS";
export const SET_PENDING_INVITATIONS = "SET_PENDING_INVITATIONS";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const SET_FRIENDS_SUCCESS = "SET_FRIENDS_SUCCESS";
